#! python
# -*- coding: utf-8 -*-
"""
    klogd
    ~~~~~

    It's a simple program to stream Syslog messages to a Kafka server.

    :copyright: (c) 2012 by Leandro Silva.
    :license: see README.
"""

import klog.server

klog.server.run()
